In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [2]:
np._version_ #current version of anaconda

AttributeError: module 'numpy' has no attribute '_version_'

### Numpy array creation form
* list
* tuple
* range

In [3]:
np.array([23,4,564])

array([ 23,   4, 564])

In [4]:
np.array(range(5,10))

array([5, 6, 7, 8, 9])

In [5]:
a=np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [6]:
print(a.shape)
print(a.dtype)
print(a.itemsize)# n0.of bytes for each items
print(a.ndim)#n0.of dimension
print(a.nbytes)# total array size in bytes


(5,)
int32
4
1
20


In [7]:
l=[1]
t=(1,)
print(type(1),type(t))

<class 'int'> <class 'tuple'>


In [8]:
a2=np.array([[1,2,3],[4,5,6],[7,8, 9]])
print(a2)
print(a2.shape)
print(a2.dtype)
print(a2.size)
print(a2.itemsize)
print(a2.ndim)
print(a2.nbytes)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32
9
4
2
36


In [9]:
print(a2.shape[0])# to print no.of rows
print(a2.shape[1])# to print no. of columns

3
3


In [10]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [11]:
a2=np.array([1,2,3,4],dtype=np.int8)
print(a2.shape)
print(a2.dtype)
print(a2.size)
print(a2.itemsize)
print(a2.ndim)
print(a2.nbytes)

(4,)
int8
4
1
1
4


In [12]:
a = np.array([1,2,34,(2**32)+1])
print(a.dtype)

int64


## Intializing arrays
* Zeros
* Ones
* full
* eye
* diag

In [14]:
a = np.array([1,54,'ss'])
print(a.dtype)
a = np.array([1,54,None])
print(a.dtype)
a = np.array([1,54,np.nan])
print(a.dtype)

<U11
object
float64


In [15]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [16]:
print(np.ones((2,3)))
print(np.ones((2,3),bool))

[[1. 1. 1.]
 [1. 1. 1.]]
[[ True  True  True]
 [ True  True  True]]


In [18]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

### Create array in a range
 * arrange
 * linspce

In [20]:
print(np.arange(5))
print(np.arange(10,100,5))
print(np.arange(5,10,0.5))


[0 1 2 3 4]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [21]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [24]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [26]:
a=np.arange(5)
b=np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]


In [28]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)


[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4.]


In [29]:
print(a*b)
print(a**b)
print(a+b)
print(a-b)
print(a/b)

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]


* Random

In [31]:
np.random.randint(50)# gives us random value from 0-50

1

In [32]:
np.random.randint(100,size=5)

array([ 3, 39, 18, 55, 96])

In [34]:
np.random.randint(50,100,size=(5,2))

array([[71, 97],
       [74, 82],
       [68, 57],
       [77, 62],
       [66, 92]])

In [36]:
np.random.random()

0.9160127030856867

In [37]:
np.random.rand(5)

array([0.07408288, 0.33528699, 0.58788426, 0.27764984, 0.27836517])

In [38]:
np.random.rand(5,3)

array([[0.85339503, 0.07539568, 0.15948891],
       [0.70456681, 0.81268971, 0.79919739],
       [0.67933601, 0.34730256, 0.62175951],
       [0.26510292, 0.46282722, 0.9391618 ],
       [0.33058507, 0.88696869, 0.37287508]])

In [39]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [40]:
r = np.arange(10,20)
np.random.shuffle(r)
r

array([14, 17, 15, 11, 13, 18, 16, 10, 12, 19])

### Array Manipulation
* np.array

In [42]:
a = np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
np.resize(a,(13,2)) # it will repeat the after the range


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [45]:
z=np.arange(20)
z.resize(13,2)
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [46]:
np.expand_dims(a,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [47]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [48]:
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
np.expand_dims(a2,1) # change from 1-2 or 2-3 dimensions

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [50]:
np.expand_dims(a2,0)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [51]:
a2.flatten() # it will convert from any dimension to 1 dimension

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.expand_dims(a2,0).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Iteration over 1d,2d and 3d arrays

In [53]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

** Indexing,Slicing,Subset

In [55]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
print(a[0])
print(a[-1])

0
19


In [57]:
print(a[2:10])
print(a[2:10:3])

[2 3 4 5 6 7 8 9]
[2 5 8]


In [58]:
print(a[[1,10,3]])

[ 1 10  3]


* Fancy Indexing or Bolean Array

In [59]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [60]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
a2=np.arange(20).reshape(5,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [62]:
print(a2[0])
print(a2[-1])
print(a2[1:3])

[0 1 2 3]
[16 17 18 19]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
print(a2[[4,3,2,1,0]])

[[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [65]:
a2[[True,False,False,True,True]]# it will print the true value rows

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
a2[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [69]:
a2[[1,3,2],[3,2,1]] # (1,3),(3,2),(2,1)

array([ 7, 14,  9])